"use client";
import { useEffect, useRef, useState, useCallback } from "react";
import { useGSAP } from "@gsap/react";
import { gsap } from "@/lib/gsap";
import { clamp } from "@/lib/tokens";
import Link from "next/link";
import PulseGrid from "./PulseGrid";

export default function Hero() {
  const root = useRef<HTMLElement>(null);
  const stage = useRef<HTMLDivElement>(null);
  const [pos, setPos] = useState(50);
  const dragging = useRef(false);

  const moveTo = useCallback((clientX: number) => {
    const r = stage.current?.getBoundingClientRect();
    if (!r) return;
    setPos(clamp(((clientX - r.left) / r.width) * 100, 6, 94));
  }, []);

  useGSAP(() => {
    // Heavy cinematic entrance — transform/opacity only
    gsap.from(".hero-rise", {
      y: 48,
      autoAlpha: 0,
      filter: "blur(8px)",
      stagger: 0.12,
      duration: 1.2,
      ease: "vanguard",
      delay: 0.35,
    });
    gsap.to(".scanner-frame", {
      y: -24,
      scrollTrigger: { trigger: ".scanner-frame", start: "top bottom", end: "bottom top", scrub: 1 },
    });
  }, { scope: root });

  return (
    <section ref={root} id="engine" className="relative min-h-[100dvh] flex flex-col justify-center px-4 pt-40 pb-24">
      <div className="mx-auto max-w-6xl w-full text-center">
        <span className="eyebrow hero-rise">
          <span className="w-1.5 h-1.5 rounded-full bg-volt animate-pulse" />
          Multi-Modal Synthetic Media Defense
        </span>

        <h1 className="hero-rise mt-8 font-display font-semibold tracking-tight text-6xl md:text-8xl leading-[1.02] max-w-6xl mx-auto w-full">
          DECODE TRUTH FROM <span className="text-transparent bg-clip-text bg-gradient-to-r from-volt via-bone to-pulse">SYNTHETIC PIXELS.</span>
        </h1>

        {/* Claims must match what is actually built. "ocular physics" described a
            channel that does not exist, and "un-hackable" is indefensible — it
            invites exactly the attack a technical reviewer will try. */}
        <p className="hero-rise mt-8 max-w-3xl mx-auto text-ash text-lg leading-relaxed">
          Four independent channels — blood-volume pulse (rPPG), speech-to-lip biomechanics,
          classical pixel forensics, and frame-by-frame analysis — combined by quality-weighted
          fusion that abstains when the evidence cannot support a verdict.
        </p>

        <div className="hero-rise mt-10 flex flex-wrap items-center justify-center gap-4">
          <Link
            href="/detect"
            className="px-7 py-3 rounded-full bg-volt text-void font-display font-semibold tracking-tight hover:opacity-90 transition-opacity"
          >
            Launch DeepGuard
          </Link>
          <a
            href="#engine"
            className="px-7 py-3 rounded-full border border-white/15 text-bone font-display tracking-tight hover:bg-white/5 transition-colors"
          >
            How it works
          </a>
        </div>
      </div>

      {/* ── Interactive Scanner Sandbox ── */}
      <div className="scanner-frame hero-rise bezel-shell mt-20 max-w-5xl mx-auto w-full">
        <div className="bezel-core !p-0 overflow-hidden">
          {/* status bar */}
          {/* Measured figures only. This bar previously showed live-looking
              metrics generated by Math.random(); the analysis now lives at
              /detect, so the landing page shows results we have actually run. */}
          <div className="flex flex-wrap items-center justify-between gap-3 px-6 py-4 border-b border-white/10">
            <div className="flex items-center gap-2 text-xs text-ash font-mono">
              <span className="w-2 h-2 rounded-full bg-volt" />
              ILLUSTRATIVE · PULSE COHERENCE ACROSS A FACE
            </div>
            <div className="flex flex-wrap gap-2 font-mono text-[11px]">
              <span className="px-3 py-1 rounded-full bg-pulse/10 border border-pulse/40 text-pulse">
                AUC 1.000 · DFDC benchmark
              </span>
              <span className="px-3 py-1 rounded-full bg-amber-500/10 border border-amber-500/40 text-amber-300">
                AUC 0.550 · in-the-wild
              </span>
              <span className="px-3 py-1 rounded-full bg-flux/10 border border-flux/30 text-purple-300">
                4 channels · abstains on weak evidence
              </span>
            </div>
          </div>

          {/* draggable split stage */}
          <div
            ref={stage}
            className="relative aspect-video select-none cursor-ew-resize touch-none bg-zinc-900"
            onPointerDown={(e) => {
              dragging.current = true;
              (e.target as Element).setPointerCapture(e.pointerId);
              moveTo(e.clientX);
            }}
            onPointerMove={(e) => dragging.current && moveTo(e.clientX)}
            onPointerUp={() => (dragging.current = false)}
          >
            {/* AUTHENTIC layer (full) */}
            <div className="absolute inset-0">
              <img
                src="/UI.jpeg"
                alt="Authentic frame"
                className="w-full h-full object-cover grayscale contrast-125 opacity-90"
              />
              <PulseGrid coherent seed={7} />
              <span className="absolute top-4 left-4 text-[10px] font-mono px-2.5 py-1 rounded-full bg-pulse/15 border border-pulse/40 text-pulse tracking-widest backdrop-blur-md">
                AUTHENTIC · COHERENT PULSE
              </span>
            </div>

            {/* FACE-SWAP layer (clipped right of handle) — incoherent */}
            <div className="absolute inset-0" style={{ clipPath: `inset(0 0 0 ${pos}%)` }}>
              <img
                src="/UI.jpeg"
                alt="Face-swap frame"
                className="w-full h-full object-cover contrast-150 opacity-80 hue-rotate-15"
              />
              <PulseGrid coherent={false} seed={99} />
              <span className="absolute top-4 right-4 text-[10px] font-mono px-2.5 py-1 rounded-full bg-red-500/15 border border-red-500/40 text-red-300 tracking-widest backdrop-blur-md">
                FACE-SWAP · PULSE SEAMS
              </span>
            </div>

            {/* divider handle */}
            <div
              className="absolute inset-y-0 w-px bg-volt/70 shadow-[0_0_24px_rgba(0,242,254,.8)]"
              style={{ left: `${pos}%` }}
            >
              <div className="absolute top-1/2 -translate-y-1/2 -translate-x-1/2 w-10 h-10 rounded-full bg-black/60 border border-volt/60 backdrop-blur flex items-center justify-center text-volt text-xs">
                ⇄
              </div>
            </div>
          </div>

          <p className="px-6 py-3 text-center text-[11px] text-ash font-mono">
            DRAG THE SEAM · LEFT = SYNCHRONIZED CAPILLARY FLOW · RIGHT = DESYNCED GRAFTED REGIONS
          </p>
        </div>
      </div>
    </section>
  );
}
